package com.turkcell.rencar_pair.feature.maps

private const val BASE_LATITUDE = 38.51740367746754
private const val BASE_LONGITUDE = 27.161930350129918

object MapsMockSource {

    val vehicles: List<NearbyVehicle> = listOf(
        NearbyVehicle(
            id = "veh-001",
            plate = "34 RNC 022",
            brand = "Renault",
            model = "Clio",
            type = VehicleType.HATCHBACK,
            status = VehicleStatus.AVAILABLE,
            pricePerDay = 850.0,
            location = GeoPoint(BASE_LATITUDE + 0.0021, BASE_LONGITUDE - 0.0014),
            distanceMeters = 250,
            fuelPercent = 72,
            tankLabel = "Dolu depo",
            rangeKm = 480,
            transmission = "Manuel",
            seatCount = 5,
            pricePerMinute = 4.50,
            pricePerHour = 180.0
        ),
        NearbyVehicle(
            id = "veh-002",
            plate = "34 ABC 118",
            brand = "Volkswagen",
            model = "Passat",
            type = VehicleType.SEDAN,
            status = VehicleStatus.AVAILABLE,
            pricePerDay = 1500.0,
            location = GeoPoint(BASE_LATITUDE - 0.0032, BASE_LONGITUDE + 0.0026),
            distanceMeters = 620,
            fuelPercent = 88,
            tankLabel = "Dolu depo",
            rangeKm = 610,
            transmission = "Otomatik",
            seatCount = 5,
            pricePerMinute = 6.30,
            pricePerHour = 250.0
        ),
        NearbyVehicle(
            id = "veh-003",
            plate = "35 SUV 341",
            brand = "Hyundai",
            model = "Tucson",
            type = VehicleType.SUV,
            status = VehicleStatus.AVAILABLE,
            pricePerDay = 1900.0,
            location = GeoPoint(BASE_LATITUDE + 0.0048, BASE_LONGITUDE + 0.0037),
            distanceMeters = 910,
            fuelPercent = 54,
            tankLabel = "Yarı dolu depo",
            rangeKm = 390,
            transmission = "Otomatik",
            seatCount = 5,
            pricePerMinute = 7.60,
            pricePerHour = 310.0
        ),
        NearbyVehicle(
            id = "veh-004",
            plate = "34 STW 076",
            brand = "Skoda",
            model = "Octavia Combi",
            type = VehicleType.STATION,
            status = VehicleStatus.AVAILABLE,
            pricePerDay = 1350.0,
            location = GeoPoint(BASE_LATITUDE - 0.0016, BASE_LONGITUDE - 0.0041),
            distanceMeters = 540,
            fuelPercent = 96,
            tankLabel = "Dolu depo",
            rangeKm = 700,
            transmission = "Manuel",
            seatCount = 5,
            pricePerMinute = 5.80,
            pricePerHour = 230.0
        ),
        NearbyVehicle(
            id = "veh-005",
            plate = "34 MNV 205",
            brand = "Renault",
            model = "Trafic",
            type = VehicleType.MINIVAN,
            status = VehicleStatus.RENTED,
            pricePerDay = 2100.0,
            location = GeoPoint(BASE_LATITUDE + 0.0063, BASE_LONGITUDE - 0.0022),
            distanceMeters = 1180,
            fuelPercent = 40,
            tankLabel = "Yarı dolu depo",
            rangeKm = 260,
            transmission = "Manuel",
            seatCount = 7,
            pricePerMinute = 8.90,
            pricePerHour = 350.0
        ),
        NearbyVehicle(
            id = "veh-006",
            plate = "34 ECO 512",
            brand = "Fiat",
            model = "Egea",
            type = VehicleType.SEDAN,
            status = VehicleStatus.AVAILABLE,
            pricePerDay = 780.0,
            location = GeoPoint(BASE_LATITUDE - 0.0044, BASE_LONGITUDE - 0.0009),
            distanceMeters = 780,
            fuelPercent = 100,
            tankLabel = "Dolu depo",
            rangeKm = 640,
            transmission = "Manuel",
            seatCount = 5,
            pricePerMinute = 3.80,
            pricePerHour = 150.0
        ),
        NearbyVehicle(
            id = "veh-007",
            plate = "35 HTC 890",
            brand = "Opel",
            model = "Corsa",
            type = VehicleType.HATCHBACK,
            status = VehicleStatus.AVAILABLE,
            pricePerDay = 700.0,
            location = GeoPoint(BASE_LATITUDE + 0.0011, BASE_LONGITUDE + 0.0052),
            distanceMeters = 430,
            fuelPercent = 65,
            tankLabel = "Yarı dolu depo",
            rangeKm = 410,
            transmission = "Manuel",
            seatCount = 5,
            pricePerMinute = 3.20,
            pricePerHour = 130.0
        ),
        NearbyVehicle(
            id = "veh-008",
            plate = "34 SUV 663",
            brand = "Toyota",
            model = "CH-R",
            type = VehicleType.SUV,
            status = VehicleStatus.MAINTENANCE,
            pricePerDay = 2000.0,
            location = GeoPoint(BASE_LATITUDE - 0.0058, BASE_LONGITUDE + 0.0044),
            distanceMeters = 1340,
            fuelPercent = 22,
            tankLabel = "Az yakıt",
            rangeKm = 140,
            transmission = "Otomatik",
            seatCount = 5,
            pricePerMinute = 8.10,
            pricePerHour = 320.0
        ),
        NearbyVehicle(
            id = "veh-009",
            plate = "34 SDN 447",
            brand = "Volkswagen",
            model = "Jetta",
            type = VehicleType.SEDAN,
            status = VehicleStatus.AVAILABLE,
            pricePerDay = 1450.0,
            location = GeoPoint(BASE_LATITUDE + 0.0028, BASE_LONGITUDE - 0.0058),
            distanceMeters = 690,
            fuelPercent = 81,
            tankLabel = "Dolu depo",
            rangeKm = 590,
            transmission = "Otomatik",
            seatCount = 5,
            pricePerMinute = 6.00,
            pricePerHour = 240.0
        ),
        NearbyVehicle(
            id = "veh-010",
            plate = "34 STW 129",
            brand = "Peugeot",
            model = "308 SW",
            type = VehicleType.STATION,
            status = VehicleStatus.AVAILABLE,
            pricePerDay = 1250.0,
            location = GeoPoint(BASE_LATITUDE - 0.0021, BASE_LONGITUDE + 0.0061),
            distanceMeters = 860,
            fuelPercent = 47,
            tankLabel = "Yarı dolu depo",
            rangeKm = 320,
            transmission = "Manuel",
            seatCount = 5,
            pricePerMinute = 5.40,
            pricePerHour = 210.0
        ),
        NearbyVehicle(
            id = "veh-011",
            plate = "35 MNV 734",
            brand = "Ford",
            model = "Tourneo Custom",
            type = VehicleType.MINIVAN,
            status = VehicleStatus.AVAILABLE,
            pricePerDay = 2250.0,
            location = GeoPoint(BASE_LATITUDE + 0.0072, BASE_LONGITUDE + 0.0018),
            distanceMeters = 1510,
            fuelPercent = 90,
            tankLabel = "Dolu depo",
            rangeKm = 560,
            transmission = "Otomatik",
            seatCount = 8,
            pricePerMinute = 9.40,
            pricePerHour = 370.0
        ),
        NearbyVehicle(
            id = "veh-012",
            plate = "34 HTC 258",
            brand = "Citroen",
            model = "C3",
            type = VehicleType.HATCHBACK,
            status = VehicleStatus.AVAILABLE,
            pricePerDay = 650.0,
            location = GeoPoint(BASE_LATITUDE - 0.0009, BASE_LONGITUDE - 0.0031),
            distanceMeters = 310,
            fuelPercent = 76,
            tankLabel = "Dolu depo",
            rangeKm = 450,
            transmission = "Manuel",
            seatCount = 5,
            pricePerMinute = 3.00,
            pricePerHour = 120.0
        )
    )
}
